#!/bin/bash
# Copies the broker identities generated by init-sqs.sh out of the running
# Compose stack for the real-broker tests:
#
#   infra/localstack/export-broker-credentials.sh && \
#     export WAGERING_TEST_BROKER_CREDENTIALS_FILE=$PWD/tmp/broker-credentials
#
# Honors COMPOSE_PROJECT_NAME. Keys change whenever the broker container restarts.
set -euo pipefail
out=${1:-tmp/broker-credentials}
mkdir -p "$(dirname "$out")"
docker compose exec -T localstack cat /broker-credentials/credentials > "$out"
chmod 600 "$out"
echo "wrote $out"
